### ISSUE TITLE
2019.1 EAP support

### ISSUE THREAD

**Issue by vilinski** [olsh/resharper-structured-logging#1]
Hi,
do you know why the plugin is not available in extension manager in ReSharper 2019.1 EAP?
Could you release a beta for it?
Or can I help somehow with it?

**Comment by olsh** [comment]
Hi @vilinski ,
The R# SDK should be upgraded to the EAP version. I'll take care of it this weekend.

**Comment by olsh** [comment]
The EAP build was submitted to the moderation and should appear in the official repository in ~2 days.
Meanwhile, you can download the binaries from the build server and install them from a local folder.

https://ci.appveyor.com/project/olsh/resharper-structured-logging/build/artifacts

Thanks 👍

**Comment by retran** [comment]
@olsh Hi,

We are noticed that extension is not working with latest EAP because of some binary-level breaking changes in API.

Would be glad if you could rebuild it with new assemblies and submit to repository :)

**Comment by olsh** [comment]
Hi @retran ,

The fixed version 2019.1.0.25 is on moderation at the moment, you can download the build [here](https://ci.appveyor.com/project/olsh/resharper-structured-logging/builds/23871496/artifacts), thanks! 👍

**Comment by retran** [comment]
@olsh Thank you!
