### ISSUE TITLE
Support for Rider 2024.2

### ISSUE THREAD

**Issue by jacobvalter** [olsh/resharper-structured-logging#109]
Please add support for Jetbrains Rider 2024.2, it is now in EAP4

**Comment by olsh** [comment]
There is an issue with the latest EAP.
Let's wait for it to be fixed.
https://youtrack.jetbrains.com/issue/RIDER-114678

There are workarounds, but I don't have time right now for that.

**Comment by jacobvalter** [comment]
Thanks for the update - just checked the mentioned JB bug and it now says 'fixed'

**Comment by olsh** [comment]
This is the answer from the JB team:

> The current plan is that it's expected to auto-fix after we publish a release package.

So, it's not fixed yet.

**Comment by manavortex** [comment]
Just came over here to report exactly this issue. 

The bug on Jetbrains side was marked as fixed 5 days ago. I'd appreciate an update, I had to update to prerelease because code formatting broke my solution analysis, and I'm muchly missing this plugin :)

**Comment by olsh** [comment]
Hi @manavortex 

The latest SDK was published 7 days ago. And the bug still there
https://www.nuget.org/packages/JetBrains.ReSharper.SDK/2024.2.0-rc01

So, the fix wasn't published yet.

**Comment by manavortex** [comment]
Ahhh... damn. :D But good to hear that you keep an eye. Thank you!

**Comment by olsh** [comment]
You can track my attempts here :)
https://github.com/olsh/resharper-structured-logging/pull/110
