### ISSUE TITLE
Doesn't work for concatenated string

### ISSUE THREAD

**Issue by M0ns1gn0r** [olsh/resharper-structured-logging#14]
Very often (almost always) logged messages are long and don't fit on one line, so they have to be split. Unfortunately, that completely breaks the extension:

![image](https://user-images.githubusercontent.com/5908454/99976243-7d4c3e80-2da3-11eb-9868-7ebde47db042.png)

**Comment by M0ns1gn0r** [comment]
BTW the standard `string.Format` analyzer does handle this scenario:

![image](https://user-images.githubusercontent.com/5908454/99976599-f0ee4b80-2da3-11eb-9baf-3e1f19b14254.png)

**Comment by olsh** [comment]
Hi @M0ns1gn0r,

I've added support for concatenated strings, and the update will be published soon (after I fix some unrelated bugs).
Meanwhile, I'd be glad if you help me with testing the feature. You can download the latest binaries [here](https://ci.appveyor.com/project/olsh/resharper-structured-logging/build/artifacts).

**Comment by olsh** [comment]
Fixed in 2020.3.0.84 and published to JetBrains repository.
Feel free to reopen the issue if you have some bugs with the new version.

**Comment by M0ns1gn0r** [comment]
@olsh sorry for the late response, everything seems to be working fine. Thank you!
