### ISSUE TITLE
In Rider, when a property starts with a non-capital letter, it crashes the page inspections

### ISSUE THREAD

**Issue by KenBonny** [olsh/resharper-structured-logging#17]
When I have a property name that starts with a non-capitalised letter, my whole page cannot be inspected anymore. Not this inspector, not any other inspector.

`_log.LogInformation("Copy file from location: {FilePath}", message.FilePath);` works fine, but
`_log.LogInformation("Copy file from location: {filePath}", message.FilePath);` will cause the problem.

**Comment by olsh** [comment]
The bug was fixed in 2020.3.2.87
Thank you 👍🏻

**Comment by KenBonny** [comment]
Cool, thanks for fixing this!
