### ISSUE TITLE
Support for Rider 2021.1

### ISSUE THREAD

**Issue by feitzi** [olsh/resharper-structured-logging#21]
This plugin does not support Rider > 2020.3.2
Is there any reason for that or can you upgrade the dependency to 2021.1

**Comment by olsh** [comment]
Hi @feitzi,
I do not use EAP personally, so that's the main reason.
I wanted to set up dependabot to automatically update to the latest EAP version, but it doesn't support pre-release versions. https://github.com/dependabot/dependabot-core/issues/2250
So, PR is welcome :)

**Comment by olsh** [comment]
Fixed in 6a4bc53d860416d1bec5edb4d3bb89b859e969d7
