### ISSUE TITLE
Compatibility for Rider 2021.2-EAP

### ISSUE THREAD

**Issue by greuelpirat** [olsh/resharper-structured-logging#35]
I just updated to Rider 2021.2-EAP, which is not supported by your plugin:

![image](https://user-images.githubusercontent.com/16866222/120422213-14eca400-c368-11eb-853b-6bd5f3241bcc.png)

Are there issues or is it just a version-check?

**Comment by olsh** [comment]
Hi @greuelpirat,

Well, honestly don't know if there are issues with the new SDK. I didn't manage to upgrade SDK to EAP because of Gradle build, and I don't have time to investigate the problem, sorry.

PR is welcome.

**Comment by greuelpirat** [comment]
@olsh 
I checked it out. But I could not build it successfully. There are some dependencies which seems to not have been published yet. I retry it later.

**Comment by mterwoord** [comment]
Now that 2021.2 is RTM ( a few hours..), any update on this? :-)

**Comment by greuelpirat** [comment]
Ui, i completly forgot about this :-(

I tried again, but I must admit, that I do not know enough about plugin development to get it work. I have no idea what `Zone requirements are not consistent across modules` means. Sorry, but I have not the time to work at this.

**Comment by olsh** [comment]
Hi guys, I don't have a Windows PC right now. So I'm unable to test/build the plugins.
I get Windows PC only in two-three weeks.
PR is welcome.

I've tried to build the plugins without tests with CI, but no success yet.
https://github.com/olsh/resharper-structured-logging/pull/40

**Comment by LarsBauer** [comment]
Are there any TODOs apart from updating the jetbrains NuGet packages? I could submit a PR.

**Comment by mterwoord** [comment]
Probably fixing remaining issues. I think the message @greuelpirat already mentioned.

**Comment by olsh** [comment]
> Are there any TODOs apart from updating the jetbrains NuGet packages? I could submit a PR.

At least the code should compile and all tests should pass without issues.

**Comment by LarsBauer** [comment]
I upgraded the NuGet packages and the local build was successful. The tests won't run locally so I tried via pipeline (#41). Now there is some kind of gradle error.  Any idea?

**Comment by olsh** [comment]
Hi @LarsBauer 

Thank you for your PR.
I believe that we can do `Trim('0', '.')` for `-PProductVersion` parameter here https://github.com/olsh/resharper-structured-logging/blob/f7ac19c8af6d15e5a2314d27a7cd9bef9082a3a1/build/Build.cs#L127

**Comment by LarsBauer** [comment]
Thanks, this helped with building the project. Now we are facing some test errors. Unfortunately I have no experience regarding JetBrain Plugin tests. Can someone have a look?

**Comment by klemmchr** [comment]
Since Rider 2021.2 is now stable, do you have any updates on this?

**Comment by jiilaa** [comment]
I took a look at the failing tests, and it looks like the _.cs.gold_-files which the tests compare, no long matches the test output. Some of the lines are different because the test output has `<overlapped> ` added to the beginning of the lines and the order of some warnings has changed. I'm not familiar with Rider plugin tests either, so I can't be sure if it is a proper fix to change the _.cs.gold_ files to match the output or is this an indication that the plugin has a problem with the new Rider and needs actual fixing.

I hope someone can fix this soon, this is a really useful plugin for me :-)

**Comment by deleteLater** [comment]
from https://www.jetbrains.com/rider/whatsnew/
![image](https://user-images.githubusercontent.com/34052208/129853438-61cfbe50-68cf-41ca-a679-6be95ab52832.png)
it seems like the Rider 2021.2 has shipped this feature

**Comment by mterwoord** [comment]
Awesome. How could I miss this? Thanks for finding this out!

**Comment by olsh** [comment]
Thanks for your help guys. 💯 

The updated extension was published to JetBrains plugin repository. Meanwhile, you can download the binaries manually https://ci.appveyor.com/project/olsh/resharper-structured-logging/builds/40434971/artifacts
