### ISSUE TITLE
False positive naming warning

### ISSUE THREAD

**Issue by vilinski** [olsh/resharper-structured-logging#4]
- Rider 2019.3.1
- Structured Logging 2019.3.1.59
- Windows 10 x64

The following code 

```csharp
var newItem = 42;
_logger.LogError("Answer is {newItem}", newItem);
```
emits a warning about property naming (false positive)

```
Property name 'newItem' does  not naming rules'. Suggested name is 'NewItem'.
```

The warning disappears if plugin is deactivated.

**Comment by olsh** [comment]
Well, this is a new rule implemented in the latest version.
https://github.com/olsh/resharper-structured-logging/blob/master/rules/InconsistentLogPropertyNaming.md

By default suggested property name should be PacalCase. The naming may be configured in the extension settings (only in R# at the moment).
![image](https://user-images.githubusercontent.com/3613592/73571359-6a1c5b00-447f-11ea-8aa0-d31daeb85a7f.png)

Sadly I have not time to implement it in Rider. PR is welcome. :)

The only workaround for you is to configure the rule in R# and save to [Team Shared settings](https://www.jetbrains.com/help/resharper/Sharing_Configuration_Options.html) or disable the rule solution-wide.

**Comment by vilinski** [comment]
Oh, seems it's not a false positive! :) Log property vs class property. Thank you for explanation. I will set the rule for my needs using R# for now.
