### ISSUE TITLE
TemplateIsNotCompileTimeConstant should ignore NameOf()

### ISSUE THREAD

**Issue by sommmen** [olsh/resharper-structured-logging#42]
Hiya,

I often have messagetemplates like:

```
_logger.LogError(e, $"Caught exception in {nameof(PostStock)}");
```

Where instead of typing `PostStock` as constant string, I tend to use `NameOf` which is useful because the name may change.
This could also include SizeOf - but i'm not sure whether that is a compile time variable as NameOf is....
The docs mention 'constants' but still...

Related:

https://github.com/olsh/resharper-structured-logging/blob/f7ac19c8af6d15e5a2314d27a7cd9bef9082a3a1/rules/TemplateIsNotCompileTimeConstantProblem.md

I would love if the warning wouldn't show up in the case of NameOf.

**Comment by olsh** [comment]
Hi @sommmen 

I believe this is the same issue https://github.com/olsh/resharper-structured-logging/issues/9
Would you mind checking the discussion and letting me know if it answers your question?

In a nutshell - the interpolation string is not constant per se.

**Comment by sommmen** [comment]
> Hi @sommmen
> 
> I believe this is the same issue #9
> Would you mind checking the discussion and letting me know if it answers your question?
> 
> In a nutshell - the interpolation string is not constant per se.

Seems you're right!

The following works:
``` csharp
_logger.LogError(e, "Caught exception in " + nameof(PostStock));
```

I'll use that from now on. Thanks for your support! 
(would be a cool refactor action to add btw)

**Comment by olsh** [comment]
> (would be a cool refactor action to add btw)

Yes, I think this is nice to have feature.
I'll probably implement it when I have some spare time.

**Comment by markusschaber** [comment]
Looks like C# 10 has constant interpolated strings, giving this issue some fresh wind:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/constant_interpolated_strings

**Comment by sommmen** [comment]
> @olsh Looks like C# 10 has constant interpolated strings, giving this issue some fresh wind: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/constant_interpolated_strings

Looks pretty good. Perhaps add a fresh issue to discuss this? Or perhaps wait when c# 10 is out.

**Comment by olsh** [comment]
The extension works correctly with constant interpolated strings already.
https://github.com/olsh/resharper-structured-logging/issues/9#issuecomment-1043276009

**Comment by sommmen** [comment]
> The extension works correctly with constant interpolated strings already. [#9 (comment)](https://github.com/olsh/resharper-structured-logging/issues/9#issuecomment-1043276009)

Lol I thought the latest version was c#9 for some reason. Funny I'll try this out tomorrow although I've now gotten used to writing logs in the concatenated version 🙃
