### ISSUE TITLE
Splitting string into multiple parts with concatenation breaks highlighting

### ISSUE THREAD

**Issue by sommmen** [olsh/resharper-structured-logging#43]
``` csharp
_logger.LogError(ex, "Caught Error whilst creating and adding " + nameof(SalesSupplyMail) + ": {EntityId}", entity.Id);
```

Shows up as:
![image](https://user-images.githubusercontent.com/8641495/128865549-b1c0519c-070d-4ca0-a059-d6a880815dae.png)

**Comment by olsh** [comment]
The highlighting feature is a built-in R#/Rider feature and the implementation doesn't contain the bug.
So, fixed in 2021.2.0.168
