### ISSUE TITLE
Add Subcategory to Issues

### ISSUE THREAD

**Issue by pinkfloydx33** [olsh/resharper-structured-logging#5]
Is it possible to add a subcategory to all of the issues? Perhaps something like "Structured Logging Misuse".

If this is something you'd be open to, I'd be glad to try my hand at it and submit a PR.

**Comment by pinkfloydx33** [comment]
To give an idea why I would like this, here's my use case:

We run inspectcode.exe as part of our PR pipelines and the only plugin we add to the vanilla run is Structured Logging. We generate a nice html report of *all* issues but we also perform analysis on a category/severity/issue basis for things we are really concerned about. We display a summary of those results in our PRs (with a link to full report) and choose to pass/fail in part. 

When we analyze the results, we allow certain thresholds based on severity/category and sometimes the issue Id. One thing we would like to enforce is that there are zero structured Logging warnings. Because all of the issues are in the general "Compiler Warnings" category, I need to add individual overrides for each IssueId this plugin can raise. It'd be nice to be able to do it at the subcategory (or category) level, which has the added bonus that I don't need to monitor for new rules. 

Adding a sub-category also means I'd get a nice "english" piece of text to display in the summary. Right now for this plugin (or any issues I'm explicitly watching for that don't have a subcategory) I display the cryptic Issue Id. I choose not to display the description of the issue itself since sometimes they're not very helpful on their own. (The ones that come from here usually have format strings in them ie `Property name '{0}' does not naming rules'. Suggested name is '{1}'` which doesn't really tell someone looking at the summary it's referring to logging. This also impacts our html report where we group by Issue and show the issue's description, unfortunately with format string placeholders. But that's a seperate topic)

**Comment by olsh** [comment]
Hi @pinkfloydx33,

Great suggestion! 👍 
I think it will be helpful in cases when you manually analyze warnings in VS too.

The PR is welcome.

> It'd be nice to be able to do it at the subcategory (or category) level, which has the added bonus that I don't need to monitor for new rules.

What's the difference between category and sub-category? I thought that only `GroupId` (category) could be specified.
https://github.com/olsh/resharper-structured-logging/blob/5976ea984838e6f520d84e3ec6b21e22f48bfde9/src/ReSharper.Structured.Logging/Highlighting/AnonymousObjectWithoutDestructuringWarning.cs#L9-L16
