### ISSUE TITLE
Possibility for configuring custom InconsistentLogPropertyNaming

### ISSUE THREAD

**Issue by olsh** [olsh/resharper-structured-logging#51]
### Discussed in https://github.com/olsh/resharper-structured-logging/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **corey-re-leased** November  4, 2021</sup>
Hi,

Within our team, we use prefixes to our Log Properties to allow for filtering in Serilog Seq.

This is demonstrated below:
`_logger.LogInformation("Starting Execution of {RLS_FunctionName}", functionName);`

Unfortunately, this is leading to InconsistentLogPropertyNaming message: suggested name is **RlsFunctionName**

I was wondering whether you could implement some sort of configuration to exclude some custom LogPropertyNaming patterns?

Thanks,
Corey</div>

**Comment by PavelFischerCoupa** [comment]
Would also like to have a possibility to configure. E.g. we use conventions from elastic for kibana: https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html And I observe many warning in out projects

**Comment by olsh** [comment]
@PavelFischerCoupa I've added the option in this release
https://github.com/olsh/resharper-structured-logging/releases/tag/2022.1.2.261
Thank you! 👍🏻

**Comment by PavelFischerCoupa** [comment]
Thank you! Will try it!
