### ISSUE TITLE
Not compatible with Rider EAP 2022.1 EAP 3

### ISSUE THREAD

**Issue by nesc58** [olsh/resharper-structured-logging#58]
Thank you for this great plugin.

The plugin should be compatible with EAP 2022.1 EAP 3

**Comment by olsh** [comment]
Hi @nesc58 

Just send an updated version for review.
Meanwhile, you can download binaries here https://ci.appveyor.com/project/olsh/resharper-structured-logging/builds/42637543/artifacts

**Comment by nesc58** [comment]
Hell yeah, it works like a charm 👍
