### ISSUE TITLE
[Suggestion] Allow custom logic to be taken into code lens by this plugin

### ISSUE THREAD

**Issue by rafek1241** [olsh/resharper-structured-logging#59]
**suggestion:** Allow custom logic to be taken into code lens by this plugin.

It could be configurable within plugin settings.

**Use case:**
We made `lazy` logging that it is not in default `Serilog` implementation and it's not taken via codelens.

Pic rel:
![image](https://user-images.githubusercontent.com/9272027/158775170-7ad51cee-54c6-4665-bb14-d2fc35e4e55c.png)

**Comment by olsh** [comment]
Hi @rafek1241 
By code lens do you mean the template syntax highlighting?

**Comment by rafek1241** [comment]
@olsh Yes, my bad :P

**Comment by olsh** [comment]
[The highlighting is a built-in feature starting from R#/Rider 2021.2](https://github.com/olsh/resharper-structured-logging/issues/35#issuecomment-900883583)

So I think you need to open an issue in the JB tracker https://youtrack.jetbrains.com/
