### ISSUE TITLE
`ToString` in parent classes is not considered

### ISSUE THREAD

**Issue by alexb5dh** [olsh/resharper-structured-logging#68]
["Complex objects with default ToString() implementation probably need to be destructured"](https://github.com/olsh/resharper-structured-logging/blob/master/rules/ComplexObjectDestructuringProblem.md) warning is shown when object inherit overriden `ToString` from base class different from `object`:

```csharp
public class A
{
    public override string ToString() => "Custom ToString";
}

public class B: A { }
```

![image](https://user-images.githubusercontent.com/4650832/183229739-ba64fe24-7fb2-4ca6-aae7-c1b3e2e3da7c.png)

**Comment by olsh** [comment]
The bug was fixed in this release.
https://github.com/olsh/resharper-structured-logging/releases/tag/2022.1.2.261
Thank you! 👍🏻
