### ISSUE TITLE
Compatibility with Rider 2022.3 EAP

### ISSUE THREAD

**Issue by Drenalol** [olsh/resharper-structured-logging#70]
The Rider 2022.3 EAP [is out](https://blog.jetbrains.com/dotnet/2022/10/07/rider-2022-3-eap-2/)!

Please, update.

**Comment by olsh** [comment]
Just sent an updated version for review.
Meanwhile, you can download binaries here https://ci.appveyor.com/project/olsh/resharper-structured-logging/builds/45012770/artifacts
