### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by dfbag7** [olsh/resharper-structured-logging#77]
When trying to update the plugin to the latest revision I'm getting this error message when restarting the IDE:
 
![picture](https://user-images.githubusercontent.com/5889364/199424590-ca98968f-13b6-4b48-a587-6705faf64bf4.png)

After restart, the plugin is still shown as needs update.

The IDE I'm using is Rider 2022.2.3.

**Comment by olsh** [comment]
Hi @dfbag7 
I'm aware of the issue, but sadly I don't know how to fix this on the plugin side, because the plugin doesn't control the installation flow.

The workaround for this is 
1. Disable the extension
2. Restart Rider
3. Update the extension

**Comment by dfbag7** [comment]
Thank you. It is worth to add this to the documentation, until fixed.

**Comment by olsh** [comment]
Let's keep the issue open for a while

**Comment by olsh** [comment]
Here is the [related issue](https://youtrack.jetbrains.com/issue/RIDER-11077), please use the [workaround](https://github.com/olsh/resharper-structured-logging/issues/77#issuecomment-1299699863) until it is fixed.
