### ISSUE TITLE
Convert to compile time constant codefix should cover more cases 

### ISSUE THREAD

**Issue by MichalBrylka** [olsh/resharper-structured-logging#87]
Hi,
The "Convert to compile time constant message template" generally works and produces nice results:
![image](https://user-images.githubusercontent.com/18634170/223559115-ca261496-92e5-4fe3-a2c9-6f3f731f81b8.png)

Where it falls short is when presented with more challenging (but sadly, more frequent) structured logging bad practice i.e.:
```cs
log.InfoFormat("Name:" + name + " age " + age);
```
No code fix is presented in such case:
![image](https://user-images.githubusercontent.com/18634170/223559568-c51a7fad-c5f1-4cfb-976f-502c3c6202ae.png)

While it might be tempting to add support for such bad-practices fixes, I'd propose to alternatively allow R# to use it's own "Convert concatenation to interpolation" action:
![image](https://user-images.githubusercontent.com/18634170/223559933-872bdae9-4b79-439e-b858-eeb07291fba3.png)

Your plugin somehow prohibits this action from displaying in suggestion list 

Would it be feasible to allow R# to propose it's own suggestions/code fixes ?

Using "Convert concatenation to interpolation" followed by your code fix would allow many ill-structured logging calls to be mended

**Comment by olsh** [comment]
Closed due to inactivity
