### ISSUE TITLE
Compatibility with Jetbrains Rider 2023.2

### ISSUE THREAD

**Issue by jacobvalter** [olsh/resharper-structured-logging#88]
Please support Rider 2023.2 - thanks!

**Comment by olsh** [comment]
Hi @jacobvalter 

Thank you for raising the issue

The update was published to the JB repository
https://plugins.jetbrains.com/plugin/12832-structured-logging/versions/stable/340475

**Comment by jacobvalter** [comment]
Hi @olsh 

me thanks for adding the support and for life-saving plugin!
